#! /usr/bin/env bash

set -e
set -o pipefail
set -x

# Install babylon specific taps, brews and casks
brew bundle --verbose --file Brewfile.babylon --no-lock

# Setup babylon specific zsh configuration
mkdir -p ~/.zshrc.d
cp -R dotfiles/.zshrc.d/babylon/* ~/.zshrc.d/
