export PATH="/Users/toby.clemson/.local/bin:$PATH"

ARTIFACTORY_PYPI_USER="${ARTIFACTORY_USER}"
ARTIFACTORY_PYPI_API_KEY="${ARTIFACTORY_API_KEY}"

export ARTIFACTORY_PYPI_USER
export ARTIFACTORY_PYPI_API_KEY
