export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="default"

plugins=(
  autojump
  aws
  bundler
  brew
  docker
  emacs
  extract
  gem
  git
  gradle
  lein
  node
  npm
  osx
  pyenv
  rake
  rbenv
  react-native
  rsync
  ruby
  terraform
  tmux
  urltools
  xcode
)

export PATH="$HOME/bin:/usr/local/bin:$PATH"
export MANPATH="/usr/local/man:$MANPATH"
export EDITOR=vi

export AUTHORS="@tobyclemson"

ssh-add -K &> /dev/null
ssh-add -A &> /dev/null

source $ZSH/oh-my-zsh.sh

echo -e "Kernel Information: " `uname -smr`
echo -e "`zsh --version`"
echo -ne "Uptime: "; uptime
echo -ne "Server time is: "; date

[[ $EMACS = t ]] && unsetopt zle

alias lla="ls -lah"
alias ber="nocorrect be rspec"

fpath=($HOME/.zsh-completions $fpath)
autoload -U compinit
compinit

eval "$(direnv hook zsh)"

export GOENV_ROOT="$HOME/.goenv"
export PATH="$GOENV_ROOT/bin:$PATH"
eval "$(goenv init -)"

export ANDROID_SDK="$HOME/Library/Android/sdk"
export ANDROID_HOME="$ANDROID_SDK"
export PATH="$ANDROID_SDK/tools:$ANDROID_SDK/platform-tools:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
