export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="default"

plugins=(ant autojump bundler brew emacs extract git gradle lein mvn osx rbenv rsync svn terminalapp textmate urltools vagrant)

export PATH=$HOME/bin:/usr/local/bin:$PATH
export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

echo -e "Kernel Information: " `uname -smr`
echo -e "`zsh --version`"
echo -ne "Uptime: "; uptime
echo -ne "Server time is: "; date

[[ $EMACS = t ]] && unsetopt zle

alias lla="ls -lah"
alias ber="nocorrect be rspec"

fpath=($HOME/.zsh-completions $fpath)
autoload -U compinit
compinit
