export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="default"

plugins=(autojump bundler brew emacs extract git gradle lein mvn osx rbenv rsync svn terminalapp textmate urltools)

export PATH="$HOME/bin:/usr/local/bin:$PATH"
export MANPATH="/usr/local/man:$MANPATH"
export EDITOR=vi

source $ZSH/oh-my-zsh.sh

echo -e "Kernel Information: " `uname -smr`
echo -e "`zsh --version`"
echo -ne "Uptime: "; uptime
echo -ne "Server time is: "; date

[[ $EMACS = t ]] && unsetopt zle

alias lla="ls -lah"
alias ber="nocorrect be rspec"

fpath=($HOME/.zsh-completions $fpath)
autoload -U compinit
compinit

export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

